src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use App\Service\UploadHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, \JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @Assert\Length(
     *     min = 2,
     *     max = 50,
     *     minMessage="Ime moze imati najmanje 2 karaktera.",
     *     maxMessage="Ime moze imati najvise 50 karaktera."
     * )
     */
    private string $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @Assert\Length(
     *     min = 2,
     *     max = 50,
     *     minMessage="Prezime moze imati najmanje 2 karaktera.",
     *     maxMessage="Prezime moze imati najvise 50 karaktera."
     * )
     */
    private string $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @Assert\Email(
     *     message = "Nepravilan format email-a. (Primer: imeprezime@mail.com )"
     * )
     */
    private string $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @Assert\Length(
     *     min = 8,
     *     max = 255,
     *     minMessage="Lozinka moze imati najmanje 8 karaktera.",
     *     maxMessage="Lozinka moze imati najvise 255 karaktera."
     * )
     */
    private ?string $password = null;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles=[];



    /**
     * @ORM\OneToMany(targetEntity=Meeting::class, mappedBy="creator")
     */
    private Collection $meetings;

    /**
     * @ORM\ManyToOne(targetEntity=Sector::class, inversedBy="users", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sector;

    /**
     * @ORM\OneToMany(targetEntity=UserInMeeting::class, mappedBy="user")
     */
    private $userInMeetings;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture = null;

    public function __construct()
    {
        $this->meetings = new ArrayCollection();
        $this->userInMeetings = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


    /**
     * @return Collection<int, Meeting>
     */
    public function getMeetings(): Collection
    {
        return $this->meetings;
    }

    public function addMeeting(Meeting $meeting): self
    {
        if (!$this->meetings->contains($meeting)) {
            $this->meetings[] = $meeting;
            $meeting->setCreator($this);
        }

        return $this;
    }

    public function removeMeeting(Meeting $meeting): self
    {
        if ($this->meetings->removeElement($meeting)) {
            // set the owning side to null (unless already changed)
            if ($meeting->getCreator() === $this) {
                $meeting->setCreator(null);
            }
        }

        return $this;
    }


    /**
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }



    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see PasswordAuthenticatedUserInterface
     */
    //public function getPassword(): ?string
    //{
    //   return null;
    //}

    public function getSector(): ?Sector
    {
        return $this->sector;
    }

    public function setSector(?Sector $sector): self
    {
        $this->sector = $sector;

        return $this;
    }

    public function getFullName():string
    {
        return $this->getFirstName() . " " . $this->getLastName();
    }

    public function getAvatar(int $size = 32):string
    {
        return 'https://ui-avatars.com/api/?' . http_build_query([
                'name'=>$this->getFirstName(),
                'size'=>$size,
                'background'=>'random',
            ]);
    }

    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload){
/*
        if($this->getFirstName() === null){
            $context->buildViolation("Unesite ime!")
                ->atPath('firstName')
                ->addViolation();
        }

        if($this->getLastName() === null){
            $context->buildViolation("Unesite prezime!")
                ->atPath('lastName')
                ->addViolation();
        }

        if ($this->getEmail() === null){
            $context->buildViolation("Unesite email!")
                ->atPath('email')
                ->addViolation();
        }elseif (!filter_var($this->getEmail(), FILTER_VALIDATE_EMAIL)){
            $context->buildViolation("Unesite validan format email-a!")
                ->atPath('email')
                ->addViolation();
        }

        if($this->getPassword() === null){
            $context->buildViolation("Unesite lozinku!")
                ->atPath('password')
                ->addViolation();
        }elseif(strlen($this->getPassword()) < 8){
            $context->buildViolation("Lozinka moze imati barem 8 karaktera!")
                ->atPath('password')
                ->addViolation();
        }

        if($this->getSector() === null){
            $context->buildViolation("Izaberite sektor!")
                ->atPath('sector')
                ->addViolation();
        }*/

    }

    /**
     * @return Collection<int, UserInMeeting>
     */
    public function getUserInMeetings(): Collection
    {
        return $this->userInMeetings;
    }

    public function addUserInMeeting(UserInMeeting $userInMeeting): self
    {
        if (!$this->userInMeetings->contains($userInMeeting)) {
            $this->userInMeetings[] = $userInMeeting;
            $userInMeeting->setUser($this);
        }

        return $this;
    }

    public function removeUserInMeeting(UserInMeeting $userInMeeting): self
    {
        if ($this->userInMeetings->removeElement($userInMeeting)) {
            // set the owning side to null (unless already changed)
            if ($userInMeeting->getUser() === $this) {
                $userInMeeting->setUser(null);
            }
        }

        return $this;
    }


    public function __toString(){
        return $this->id . "";
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
    public function getPicturePath(){
        return './uploads/'.UploadHelper::PROFILE_IMAGES.'/'.$this->getPicture();
    }

    public function jsonSerialize()
    {
        return array(
            'name' => $this->getFullName(),
            'sector' => $this->getSector()->getName()
        );
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
       {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand navbar-dark sticky-top {{ app.session.flashBag.peek('success')|length > 0 ? '' : 'mb-4' }}" style="background-image: linear-gradient(to top,#0089DE, #004B7A); ">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('app_home') }}" style="padding-left: 15px; font-weight: bold; font-size: 22pt;">info<span style="color: #F482D4">sala</span></a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto ">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_showall_room') }}">Rezerviši salu</a>
                        </li>
                        {% if is_granted('ROLE_ADMIN') %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" href="" >Admin</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_users') }}">Korisnici</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_meetings') }}">Sastanci</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_room') }}">Sale</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_sectors') }}">Sektori</a></li>
                                </ul>
                            </li>
                        {% elseif is_granted('ROLE_CHIEF') %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" href="" >Šef-admin</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_users') }}">Korisnici</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_meetings') }}">Sastanci</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_showall_room') }}">Sale</a></li>
                                    <li><a class="dropdown-item" href="{{ path('admin_room_schedule') }}">Raspored za sale</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        {% set message = false %}
                        {% set messageNumber = 0 %}
                        {% for m in app.user.userInMeetings %}
                            {% if m.isGoing == 0 %}
                                {% set message = true %}
                                {% set messageNumber = messageNumber + 1 %}
                            {% endif %}
                        {% endfor %}
                        <div class="dropdown ">

                            <a class= "me-3 position-relative"
                                    id="user-dropdown"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false"
                                    style="text-decoration: none">
                                {% if app.user.picture %}
                                    <img src=" {{ asset(app.user.picturePath) }}
                                    " alt="{{ app.user.fullName }}" width="45" height="45">
                                {% else %}
                                    <img src="{{ app.user.avatar }}" alt="{{ app.user.fullName }} Avatar">
                                {% endif %}
                                {% if message %}
                                    <span class="position-absolute top-0 start-100 translate-middle badge
                                    border border-light rounded-circle bg-danger p-2">
                                    <span class="visually-hidden">New alerts</span>
                                    </span>
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="user-dropdown">
                                <li><a href="{{ path('app_user_created_meetings') }}" class="dropdown-item">Moji kreirani sastanci</a></li>
                                <li><a href="{{ path('app_user_meeting_requests') }}" class="dropdown-item">Pozivi za sastanke
                                        {% if message %}
                                            <span class="badge bg-danger p-1">
                                            {{ messageNumber }}
                                            </span>
                                        {% endif %}
                                    </a>
                                </li>
                                <li><a href="{{ path('app_user_future_meetings') }}" class="dropdown-item">Svi budući sastanci</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a href="{{ path('app_user_profile') }}" class="dropdown-item">Moj profil</a></li>
                                <li><a href="{{ path('app_user_change_password') }}" class="dropdown-item">Promeni lozinku</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a href="{{ path('app_logout') }}" class="dropdown-item">Odjavi se</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{{ path('app_login') }}" class="btn btn-sm btn-outline-light me-3" type="button" >Prijava</a>
                        <a href="{{ path('app_signup')}}" class="btn btn-sm btn-outline-light me-3" type="button" >Registracija</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% block body %}{% endblock %}
    </body>
</html>